import os

import pytest
from fastapi.testclient import TestClient

from ddt_mirror.core.engine import ProjectData
from ddt_mirror.core.flatten import flatten_tags
from ddt_mirror.core.persist import SidecarState
from ddt_mirror.web import server


@pytest.fixture()
def client(parsed, tmp_path):
    types, tags = parsed
    leaves, warnings = flatten_tags(tags, types)
    server.S.data = ProjectData(types=types, tags=tags, leaves=leaves,
                                warnings=warnings)
    server.S.state = SidecarState()
    server.S.state.selected_types = ["PUMP_T", "INT", "BOOL", "REAL"]
    server.S.project_path = str(tmp_path / "plant.stu")
    server.S.plan = server.S.new_alloc = server.S.t2 = None
    server.S.activity.clear()
    return TestClient(server.app)


def test_status_and_project(client):
    s = client.get("/api/status").json()
    assert s["project"] == "plant.stu" and s["leaves"] > 0
    p = client.get("/api/project").json()
    assert p["ddt_types"] >= 1
    assert any(t["type"] == "PUMP_T" for t in p["types"])


def test_variables_rows_carry_selection_keys(client):
    v = client.get("/api/variables").json()
    row = next(r for r in v["rows"] if r["path"] == "Pump1.Cmd")
    assert row["access"] == "read_write"          # naming convention
    assert row["type_key"] == "PUMP_T|Cmd"
    assert row["var_key"] == "!Pump1.Cmd"
    assert row["checked"] is True


def test_selection_snapshot_classifies_type_level(client):
    v = client.get("/api/variables").json()
    mode_paths = [r["path"] for r in v["rows"]
                  if r["type_key"] == "PUMP_T|Ctrl.Mode"]
    assert len(mode_paths) == 2                   # both pump instances
    r = client.post("/api/selection", json={
        "selected_types": ["PUMP_T", "INT", "BOOL", "REAL"],
        "unchecked": mode_paths + ["Pump1.Flow_PV"],
        "access_overrides": {"PUMP_T|Running": "read_write"},
    }).json()
    assert r["type_level"] == 1 and r["per_var"] == 1
    st = server.S.state
    assert st.deselected_type_members == ["PUMP_T|Ctrl.Mode"]
    assert st.deselected_leaves == ["Pump1.Flow_PV"]
    assert st.access_overrides["PUMP_T|Running"] == "read_write"


def test_plc_preview_is_pure_and_complete(client):
    p = client.post("/api/plc/preview", json={}).json()
    assert "GENERATED BY DDT MIRROR" in p["st"]
    assert p["csv"].count("\n") > 5
    assert all(v["address"].startswith("%MW") for v in p["new_variables"])
    # nothing persisted: preview never burns addresses
    assert server.S.state.alloc.leaves == {}


def test_rtu_assign_validates_input(client):
    r = client.post("/api/rtu/assign", json={
        "src_xls": "C:\\nope\\missing.xls", "mode": "logic"})
    assert r.status_code == 400
    r = client.post("/api/rtu/assign", json={
        "src_xls": __file__, "mode": "scanner", "device": ""})
    assert r.status_code == 400


def test_rtu_assign_scanner_end_to_end(client, tmp_path):
    from test_scanner import _make_t2_workbook

    src = tmp_path / "rtu.xls"
    _make_t2_workbook(src)
    r = client.post("/api/rtu/assign", json={
        "src_xls": str(src), "mode": "scanner", "device": "PLC_Rack"})
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["mode"] == "scanner" and body["created"] > 0
    assert "PlcRegister" in body["map_csv"]
    assert server.S.t2 is not None                # staged for generate


def test_generate_requires_preview(client):
    r = client.post("/api/plc/generate", json={})
    assert r.status_code == 409


def test_open_rejects_missing_file(client):
    r = client.post("/api/open", json={"path": "C:\\nope\\x.stu"})
    assert r.status_code == 400


def test_index_served(client):
    r = client.get("/")
    assert r.status_code == 200
    assert "DDT Mirror" in r.text
