import os

from ddt_mirror.core.adopt import (
    GeneratedSection, MIRROR_COMMENT_PREFIX, _type_words,
    find_generated_sections, load_or_recover_sidecar, recover_alloc,
    scan_reserved,
)
from ddt_mirror.core.allocator import AllocEntry, AllocState, allocate
from ddt_mirror.core.engine import ProjectData, build_plan
from ddt_mirror.core.flatten import flatten_tags
from ddt_mirror.core.model import LeafKind, Tag
from ddt_mirror.core.persist import SidecarState, save_sidecar

PROGRAM_XML = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PGMExchangeFile>
\t<program>
\t\t<identProgram name="Legacy_Ctrl" type="section" task="MAST"></identProgram>
\t\t<STSource>M_Run := %M300;
%MW7000 := Line_Speed;
%MD7100 := SomeReal;
IF %MW42.3 THEN M := 1; END_IF;</STSource>
\t</program>
\t<program>
\t\t<identProgram name="HMI_MIRROR" type="section" task="MAST"></identProgram>
\t\t<STSource>(* GENERATED BY DDT MIRROR v0.0 - DO NOT EDIT *)
%MW9999 := Pump1.Flow;</STSource>
\t</program>
</PGMExchangeFile>
"""


def test_type_words_spans():
    assert _type_words("INT") == 1
    assert _type_words("REAL") == 2
    assert _type_words("ARRAY[0..9] OF INT") == 10
    assert _type_words("ARRAY[0..4] OF REAL") == 10
    assert _type_words("ARRAY[0..1,0..2] OF INT") == 6
    assert _type_words("STRING[10]") == 6
    assert _type_words("STRING") == 9
    assert _type_words("BOOL") == 1


def test_find_generated_sections():
    secs = find_generated_sections(PROGRAM_XML)
    assert [(s.task, s.name) for s in secs] == [("MAST", "HMI_MIRROR")]
    assert "%MW9999" in secs[0].st_text
    assert find_generated_sections(None) == []


def test_scan_reserved_covers_located_and_literals():
    tags = [
        Tag("Speed", "INT", address="%MW200"),
        Tag("Level", "REAL", address="%MW500"),          # spans 500-501
        Tag("Buf", "ARRAY[0..9] OF INT", address="%MW600"),  # 600-609
        Tag("Run", "BOOL", address="%M50"),
        Tag("HMI_X", "REAL", comment=f"{MIRROR_COMMENT_PREFIX}P.X",
            address="%MW9000"),                          # ours: excluded
        Tag("Unlocated", "INT"),
    ]
    usage = scan_reserved(tags, PROGRAM_XML, {"HMI_MIRROR"})
    # literals: %M300, %MW7000, %MD7100 (spans 7100-7101), %MW42.3
    assert usage.max_bit == 300
    assert usage.max_word == 7101
    assert usage.n_located == 4
    # our generated section's %MW9999 must NOT raise the floor
    assert usage.max_word < 9000 or usage.max_word == 7101


def test_allocate_respects_floors_without_moving_existing():
    state = AllocState()
    state.leaves["Old.Tag"] = AllocEntry("%MW1000", "word1", "read")
    state.next_word, state.next_bit = 1001, 100
    tags = [Tag("Old_Tag_Src", "INT"), Tag("NewTag", "INT"),
            Tag("NewBool", "BOOL")]
    leaves, _ = flatten_tags(tags, {})
    # rename first leaf's path to match the existing entry
    leaves[0].instance = "Old.Tag"
    got = allocate(state, leaves, bit_floor=500, word_floor=7102)
    by_path = {a.leaf.full_path: a.address for a in got}
    assert by_path["Old.Tag"] == "%MW1000"      # never moved
    assert by_path["NewTag"] == "%MW7102"       # above the floor
    assert by_path["NewBool"] == "%M500"


def _mirror_tags_from_plan(plan) -> list[Tag]:
    return [Tag(v["name"], v["type_name"], comment=v["comment"],
                address=v["address"]) for v in plan.new_variables]


def _data(parsed) -> ProjectData:
    types, tags = parsed
    leaves, warnings = flatten_tags(tags, types)
    return ProjectData(types=types, tags=tags, leaves=leaves,
                       warnings=warnings)


def test_recovery_round_trip(parsed, tmp_path):
    """generate -> lose the sidecar -> recover -> regenerate must reproduce
    every non-premapped address and access direction exactly."""
    data = _data(parsed)
    state = SidecarState()
    state.selected_types = ["PUMP_T", "INT", "BOOL", "REAL"]
    state.access_overrides["!Pump1.Ctrl.Mode"] = "read_write"  # flipped
    plan1, alloc1 = build_plan(data, state, timestamp="t0")

    # second scan of the same project: mirror vars now exist as located tags
    data2 = _data(parsed)
    data2.tags = list(data2.tags) + _mirror_tags_from_plan(plan1)
    data2.generated_sections = [
        GeneratedSection("MAST", "HMI_MIRROR", plan1.st_source)]

    project = str(tmp_path / "site.stu")
    state2, report = load_or_recover_sidecar(project, data2)
    assert report, "recovery should report what it did"
    assert state2.access_overrides.get("!Pump1.Ctrl.Mode") == "read_write"

    plan2, _ = build_plan(data2, state2, timestamp="t0")
    addr1 = {a.leaf.full_path: (a.address, a.leaf.access)
             for a in plan1.assignments if not a.premapped}
    addr2 = {a.leaf.full_path: (a.address, a.leaf.access)
             for a in plan2.assignments if not a.premapped}
    assert addr2 == addr1


def test_recovery_reports_deleted_tags(parsed, tmp_path):
    data = _data(parsed)
    st_text = ("(* GENERATED BY DDT MIRROR *)\n"
               "%MW1000 := Ghost.Tag;\n")
    data.generated_sections = [GeneratedSection("MAST", "HMI_MIRROR", st_text)]
    state, report = load_or_recover_sidecar(str(tmp_path / "p.stu"), data)
    assert "Ghost.Tag" in state.alloc.leaves        # address stays reserved
    assert any("no longer exist" in line for line in report)


def test_existing_sidecar_wins_over_recovery(parsed, tmp_path):
    data = _data(parsed)
    data.generated_sections = [
        GeneratedSection("MAST", "HMI_MIRROR", "%MW1234 := X.Y;")]
    project = str(tmp_path / "p.stu")
    existing = SidecarState()
    existing.selected_types = ["PUMP_T"]
    save_sidecar(project, existing)
    state, report = load_or_recover_sidecar(project, data)
    assert report == []
    assert state.selected_types == ["PUMP_T"]
    assert "X.Y" not in state.alloc.leaves


def test_recover_alloc_parses_all_copy_shapes():
    tags = [Tag("HMI_P_Flow", "REAL", comment=f"{MIRROR_COMMENT_PREFIX}P.Flow",
                address="%MW1000"),
            Tag("HMI_P_Cnt", "UINT", comment=f"{MIRROR_COMMENT_PREFIX}P.Cnt",
                address="%MW1002")]
    st = "\n".join([
        "(* GENERATED BY DDT MIRROR v9 *)",
        "P.Cmd := %M100;",                       # RW direct bit
        "%MW1005 := P.Mode;",                    # READ direct word
        "HMI_P_Flow := P.Flow;  (* %MW1000 *)",  # READ via mirror (WORD2)
        "P.Cnt := HMI_P_Cnt;  (* %MW1002 *)",    # RW via mirror (UINT)
        "not_a_copy_line();",
    ])
    rec = recover_alloc(st, tags)
    e = rec.alloc.leaves
    assert e["P.Cmd"].address == "%M100" and e["P.Cmd"].access == "read_write"
    assert e["P.Cmd"].kind == LeafKind.BIT.value
    assert e["P.Mode"].address == "%MW1005" and e["P.Mode"].access == "read"
    assert e["P.Flow"].kind == LeafKind.WORD2.value
    assert e["P.Cnt"].kind == LeafKind.WORD1.value
    assert e["P.Cnt"].access == "read_write"
    assert rec.alloc.next_word == 1006  # above the highest recovered word
    assert rec.alloc.next_bit == 101
