"""Brownfield adoption: make upgrades on site backups safe.

Two mechanisms, both driven from the project's own artifacts:

1. **Reserved-usage scan** — every %M/%MW/%MD/%MF a site project already
   uses (located variable declarations AND literals inside logic code)
   raises the allocator's starting floor, so new mirrors never collide
   with hand-written addressing. Our own artifacts (mirror variables by
   their comment marker, generated sections by their header) are excluded
   so regeneration does not ratchet the floor.

2. **Sidecar recovery** — the generated ST section is self-describing
   (every copy line is a tag<->address pair; mirror variables carry the
   'HMI mirror of <path>' comment), so a lost `<project>.hmimirror.json`
   is reconstructed losslessly for all active assignments. Tombstoned /
   dead slots are unrecoverable; the reserved-usage floor covers them.
"""

from __future__ import annotations

import math
import os
import re
from dataclasses import dataclass, field

from lxml import etree

from .allocator import AllocState, AllocEntry
from .model import Access, LeafKind, Tag, leaf_kind
from .persist import SidecarState, Settings, load_sidecar, sidecar_path

# must match codegen.transfer.MIRROR_COMMENT_PREFIX (kept apart to avoid a
# core -> codegen import)
MIRROR_COMMENT_PREFIX = "HMI mirror of "
MIRROR_HEADER_MARKER = "GENERATED BY DDT MIRROR"

_ADDR_RE = re.compile(r"%(MW|MD|MF|M)(\d+)", re.IGNORECASE)
_ARRAY_RE = re.compile(
    r"^\s*ARRAY\s*\[([^\]]+)\]\s*OF\s+(\w+)", re.IGNORECASE)
_STRING_RE = re.compile(r"^\s*STRING(?:\s*\[\s*(\d+)\s*\])?", re.IGNORECASE)
_COPY_RE = re.compile(
    r"^\s*([%A-Za-z_][\w.%]*)\s*:=\s*([%A-Za-z_][\w.%]*)\s*;"
    r"(?:\s*\(\*\s*(%\w+)\s*\*\))?\s*$")

_ONE_WORD = {"INT", "UINT", "WORD"}
_TWO_WORD = {"DINT", "UDINT", "DWORD", "REAL", "TIME", "DATE", "TOD", "DT"}


@dataclass
class GeneratedSection:
    task: str
    name: str
    st_text: str


@dataclass
class ReservedUsage:
    """Highest %M / %MW indices the project already uses (foreign usage
    only — our own mirrors are excluded)."""
    max_bit: int = -1
    max_word: int = -1
    n_located: int = 0
    n_literals: int = 0

    @property
    def bit_floor(self) -> int:
        return self.max_bit + 1

    @property
    def word_floor(self) -> int:
        return self.max_word + 1


def _type_words(type_name: str) -> int:
    """%MW span of a located variable of this type (conservative)."""
    t = type_name.strip().upper()
    if t in _ONE_WORD:
        return 1
    if t in _TWO_WORD:
        return 2
    m = _ARRAY_RE.match(type_name)
    if m:
        count = 1
        for dim in m.group(1).split(","):
            b = re.match(r"\s*(-?\d+)\s*\.\.\s*(-?\d+)\s*$", dim)
            if b:
                count *= abs(int(b.group(2)) - int(b.group(1))) + 1
        return count * max(_type_words(m.group(2)), 1)
    m = _STRING_RE.match(type_name)
    if m:
        chars = int(m.group(1)) if m.group(1) else 16
        return math.ceil((chars + 2) / 2)
    return 1


def find_generated_sections(program_xml: str | None) -> list[GeneratedSection]:
    """Sections carrying our header marker, wherever they are and whatever
    they were renamed to."""
    if not program_xml:
        return []
    root = etree.fromstring(program_xml.encode("utf-8"))
    out: list[GeneratedSection] = []
    for prog in root.iter("program"):
        src = prog.find("STSource")
        if src is None or not src.text or MIRROR_HEADER_MARKER not in src.text:
            continue
        ident = prog.find("identProgram")
        out.append(GeneratedSection(
            task=ident.get("task", "MAST") if ident is not None else "MAST",
            name=ident.get("name", "") if ident is not None else "",
            st_text=src.text,
        ))
    return out


def scan_reserved(
    tags: list[Tag],
    program_xml: str | None,
    exclude_sections: set[str] = frozenset(),
) -> ReservedUsage:
    """Foreign %M/%MW usage: located declarations + code literals.

    `exclude_sections` are OUR generated sections (by name); mirror
    variables are excluded by their comment marker.
    """
    usage = ReservedUsage()

    def note(space: str, index: int, words: int = 1) -> None:
        space = space.upper()
        if space == "M":
            usage.max_bit = max(usage.max_bit, index)
        else:  # MW / MD / MF all live in word memory
            span = 2 if space in ("MD", "MF") else words
            usage.max_word = max(usage.max_word, index + span - 1)

    for tag in tags:
        if tag.comment.startswith(MIRROR_COMMENT_PREFIX):
            continue  # our own mirror variable
        m = _ADDR_RE.match((tag.address or "").strip())
        if not m:
            continue
        usage.n_located += 1
        note(m.group(1), int(m.group(2)), _type_words(tag.type_name))

    if program_xml:
        root = etree.fromstring(program_xml.encode("utf-8"))
        for prog in list(root.iter("program")):
            ident = prog.find("identProgram")
            name = ident.get("name", "") if ident is not None else ""
            if name.lower() in {s.lower() for s in exclude_sections}:
                parent = prog.getparent()
                if parent is not None:
                    parent.remove(prog)
        blob = etree.tostring(root, encoding="unicode")
        for m in _ADDR_RE.finditer(blob):
            usage.n_literals += 1
            note(m.group(1), int(m.group(2)))
    return usage


# ------------------------------------------------------------------ recovery

@dataclass
class RecoveredState:
    alloc: AllocState = field(default_factory=AllocState)
    access_overrides: dict[str, str] = field(default_factory=dict)
    selected_types: list[str] = field(default_factory=list)
    n_copies: int = 0
    warnings: list[str] = field(default_factory=list)


def recover_alloc(
    st_text: str,
    tags: list[Tag],
    settings: Settings | None = None,
) -> RecoveredState:
    """Rebuild allocation state from one generated ST section.

    Copy-line grammar (stgen._copy_line):
      READ direct:      %ADDR := Tag.Path;
      R/W  direct:      Tag.Path := %ADDR;
      READ via mirror:  HMI_Var := Tag.Path;  (* %ADDR *)
      R/W  via mirror:  Tag.Path := HMI_Var;  (* %ADDR *)
    Mirror variables are identified through their 'HMI mirror of <path>'
    comment in the variables export (name AND type => leaf kind).
    """
    settings = settings or Settings()
    rec = RecoveredState()
    mirror_vars: dict[str, Tag] = {
        t.name: t for t in tags
        if t.comment.startswith(MIRROR_COMMENT_PREFIX)
    }

    def kind_for(address: str, var: Tag | None) -> str | None:
        if var is not None:
            k = leaf_kind(var.type_name)
            return k.value if k else None
        space = _ADDR_RE.match(address)
        if not space:
            return None
        return (LeafKind.BIT if space.group(1).upper() == "M"
                else LeafKind.WORD1).value

    def add(path: str, address: str, access: Access, var: Tag | None) -> None:
        kind = kind_for(address, var)
        if kind is None:
            rec.warnings.append(
                f"{path}: could not derive kind for '{address}' - skipped")
            return
        rec.alloc.leaves[path] = AllocEntry(address, kind, access.value)
        rec.access_overrides[f"!{path}"] = access.value
        rec.n_copies += 1

    for raw in st_text.splitlines():
        m = _COPY_RE.match(raw)
        if not m:
            continue
        lhs, rhs, addr_comment = m.group(1), m.group(2), m.group(3)
        if lhs.startswith("%"):
            add(rhs, lhs.upper(), Access.READ, None)
        elif rhs.startswith("%"):
            add(lhs, rhs.upper(), Access.READ_WRITE, None)
        elif lhs in mirror_vars:
            var = mirror_vars[lhs]
            addr = (addr_comment or var.address or "").upper()
            add(rhs, addr, Access.READ, var)
        elif rhs in mirror_vars:
            var = mirror_vars[rhs]
            addr = (addr_comment or var.address or "").upper()
            add(lhs, addr, Access.READ_WRITE, var)
        elif addr_comment:
            rec.warnings.append(
                f"copy line references '{addr_comment}' but neither side is "
                f"a known mirror variable (deleted?): {raw.strip()}")

    # high-water marks above everything recovered
    max_bit, max_word = -1, -1
    for entry in rec.alloc.leaves.values():
        m = _ADDR_RE.match(entry.address)
        if not m:
            continue
        idx = int(m.group(2))
        if m.group(1).upper() == "M":
            max_bit = max(max_bit, idx)
        else:
            span = 2 if entry.kind == LeafKind.WORD2.value else 1
            max_word = max(max_word, idx + span - 1)
    rec.alloc.base_bit = settings.base_bit
    rec.alloc.base_word = settings.base_word
    rec.alloc.next_bit = max(settings.base_bit, max_bit + 1)
    rec.alloc.next_word = max(settings.base_word, max_word + 1)
    return rec


def load_or_recover_sidecar(
    project_path: str,
    data,  # engine.ProjectData (untyped to avoid a circular import)
) -> tuple[SidecarState, list[str]]:
    """The sidecar if it exists; otherwise reconstruct one from the
    project's generated artifacts. Returns (state, report_lines) —
    report_lines is empty when nothing had to be recovered."""
    if os.path.isfile(sidecar_path(project_path)):
        return load_sidecar(project_path), []

    sections = data.generated_sections
    if not sections:
        return SidecarState(), []

    state = SidecarState()
    report: list[str] = [
        f"No sidecar found next to the project, but {len(sections)} "
        "generated mirror section(s) exist - recovered the address map "
        "from the project itself:"]
    for sec in sections:
        rec = recover_alloc(sec.st_text, data.tags, state.settings)
        state.alloc.leaves.update(rec.alloc.leaves)
        state.access_overrides.update(rec.access_overrides)
        state.alloc.next_bit = max(state.alloc.next_bit or 0, rec.alloc.next_bit)
        state.alloc.next_word = max(state.alloc.next_word or 0,
                                    rec.alloc.next_word)
        report.append(f"  - section '{sec.name}' ({sec.task}): "
                      f"{rec.n_copies} assignments recovered")
        report.extend(f"  ! {w}" for w in rec.warnings)
        if sec.name and sec.name != state.settings.section_name:
            state.settings.section_name = sec.name
            state.settings.task_name = sec.task

    # reselect the types of every recovered instance so the next generate
    # reuses the recovered addresses instead of tombstoning them
    by_path = {leaf.full_path: leaf for leaf in data.leaves}
    types_seen: list[str] = []
    missing = 0
    for path in state.alloc.leaves:
        leaf = by_path.get(path)
        if leaf is None:
            missing += 1
            continue
        t = leaf.ddt_type or leaf.type_name
        if t not in types_seen:
            types_seen.append(t)
    state.selected_types = sorted(types_seen)
    if missing:
        report.append(
            f"  ! {missing} recovered tag(s) no longer exist in the project "
            "(renamed/deleted) - their addresses stay reserved, never reused")
    report.append(
        "Review the selection pages before generating: per-member "
        "deselections and tombstoned/dead slots are not recoverable "
        "(existing addresses are still never reused). Recovered Read / "
        "Read-Write directions were saved as per-variable overrides.")
    return state, report
