"""Generate the HMI_MIRROR ST section and mirror-variable names.

Copy direction follows HMI access:
- READ (HMI displays):   address := Tag;   (PLC publishes, HMI only reads)
- READ_WRITE (HMI writes): Tag := address; (HMI owns the address, PLC consumes)

Read/Write copies come first, Read copies last. Every address has exactly one
writer (the HMI or this section, never both), so no ordering hazard exists.

WORD2 leaves (REAL/32-bit) can't be assigned to a bare %MW word in ST, so they
go through a created located variable of the same type; BIT/WORD1 leaves use
%M/%MW literals directly.
"""

from __future__ import annotations

import hashlib
import re

from .model import Access, Assignment

CE_MAX_IDENT = 32
_INVALID_CHARS = re.compile(r"[^A-Za-z0-9_]")

HEADER_TEMPLATE = """\
(* ==============================================================
   GENERATED BY DDT MIRROR v{version} - DO NOT EDIT BY HAND.
   Regenerated in full on every run; manual edits will be lost.
   Project: {project}
   Generated: {timestamp}
   Read/Write tags (HMI writes) are copied address -> tag first;
   Read tags (HMI displays) are copied tag -> address last.
   ============================================================== *)
"""


def mirror_var_name(full_path: str, prefix: str = "HMI_") -> str:
    """Located mirror-variable name within CE's 32-char identifier limit.

    CE (default settings) rejects consecutive underscores (E1219) and
    trailing underscores, so collapse/strip them — including at the
    truncation seam where the hash suffix is appended.
    """
    body = _INVALID_CHARS.sub("_", full_path.replace(".", "_"))
    name = re.sub(r"_+", "_", prefix + body).strip("_")
    if len(name) <= CE_MAX_IDENT:
        return name
    digest = hashlib.sha1(name.encode("utf-8")).hexdigest()[:4].upper()
    trunk = name[: CE_MAX_IDENT - 5].rstrip("_")
    return f"{trunk}_{digest}"


def _copy_line(a: Assignment) -> str:
    if a.leaf.needs_var:
        # located mirror variable; remind the reader where it lives
        target, suffix = a.mirror_var, f"  (* {a.address} *)"
    else:
        target, suffix = a.address, ""
    if a.leaf.access is Access.READ_WRITE:
        return f"{a.leaf.full_path} := {target};{suffix}"
    return f"{target} := {a.leaf.full_path};{suffix}"


def generate_st(
    assignments: list[Assignment],
    project: str = "",
    version: str = "0.1.0",
    timestamp: str = "",
) -> str:
    lines = [HEADER_TEMPLATE.format(version=version, project=project or "-",
                                    timestamp=timestamp or "-")]
    live = [a for a in assignments if not a.premapped]

    rw = [a for a in live if a.leaf.access is Access.READ_WRITE]
    rd = [a for a in live if a.leaf.access is Access.READ]

    lines.append("(* --- HMI -> PLC : Read/Write tags (commands / setpoints) --- *)")
    lines.extend(_copy_line(a) for a in rw)
    lines.append("")
    lines.append("(* --- PLC -> HMI : Read tags (statuses / process values) --- *)")
    lines.extend(_copy_line(a) for a in rd)
    lines.append("")
    return "\n".join(lines)
